### ISSUE TITLE
Vulnerabilità sul download dei file

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#112]
Mettendo i file del PCTO nella cartella static anche chi non è loggato riesce a scaricare i file senza problemi, propongo di utilizzare un'altra cartella, leggere il file e poi mandare il file sotto forma di buffer usando l'header application/msword.
Potremmo anche usare semplicemente il buffer senza salvare il file così da risparmiare spazio sulla VM

Per provare la vulnerabilità basta generare un DOCX dalla vista PCTO Aziende, eseguire il logout e scaricare il pdf conoscendo il percorso, ad esempio: http://localhost:5173/pcto_output/01-Convenzione-generale-1.docx

**Comment by profmancusoa** [comment]
- si il funzionamento descritto è come si comporta al momento
- lo riteniamo un problema? in realtà il problema è che il file generato non viene cancellato :)
- in static non ci sono informazioni particolari
- però dobbiamo pensare ad una soluzione se lo riteniamo un problema
- la soluzione che proponi non è generale ma specifica per il file docx
-

**Comment by Andrea-Canale** [comment]
Potremmo usare l'header application/octet-stream che indica un file binario di qualsiasi tipo

**Comment by Andrea-Canale** [comment]
Comunque penso non sia sicuro lasciare i download accessibili a tutti perchè nel documento ci sono dati "sensibili" che uno studente non dovrebbe vedere

**Comment by profmancusoa** [comment]
- abbiamo chiarito che il problema è solo il file e non tutta la directory static

**Comment by profmancusoa** [comment]
- risolto. grazie @Andrea-Canale
