### ISSUE TITLE
Sezione tools e applicazione join PDF

### ISSUE THREAD

**Issue by MarcoCellini** [ittagnelli/SARP#129]
Creazione della pagina dove poter caricare i file .pdf o .docx per trasformarli in un unico pdf pronto per la stampa in fronte e retro.

**Comment by MarcoCellini** [comment]
@profmancusoa la mia idea sarebbe di fare una pagina che raccoglie tutti i tools utili per i professori e non. 
(una sorta di raccoglitore di tools)
Va bene o lei pensava a qualcosa di diverso?

**Comment by profmancusoa** [comment]
- si può essere una buona idea
- iniziamo con il preparatore di verifiche :)

**Comment by profmancusoa** [comment]
- come procede?
