### ISSUE TITLE
Stagisti troppo vicini

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#147]
- nella view PCTO-> Stage se ci sono più di 10 stagisti le foto sono troppo attacchate
- organizzare in una matrice di 8 colonne
- aumentare lievemente il padding verticale tra le immagini

![image](https://user-images.githubusercontent.com/111191978/214693569-0b3a9cf7-452e-4df4-8f67-2fb8f6bdf9f0.png)

**Comment by MarcoCellini** [comment]
https://github.com/ittagnelli/SARP/pull/149
