### ISSUE TITLE
Aggiungi modale apre l'aggiornamento in alcuni casi

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#186]
Se noi proviamo in una vista, ad esempio stage, a modificare un record, poi chiudere il modale e cliccare aggiungi stage verrà mostrato il modifica e non l'aggingi

https://user-images.githubusercontent.com/99402143/221304922-039e0df6-905e-4c9a-8bce-35ec6faf905d.mov

**Comment by profmancusoa** [comment]
-  ottimo non avevo mai notato.
- direi che non viene aggiornato correttamente lo stato e SARP pensa che siamo ancora in update e non in create

**Comment by profmancusoa** [comment]
- ho notato che il comportamento è presente in tutte le viste: utenti, aziende, etc....
- applicare la soluzione in tutte le viste in cui è presente

**Comment by profmancusoa** [comment]
bene!
