### ISSUE TITLE
Comprimere i certificati sicurezza sul lavoro

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#192]
Immaginiamo di dover generare i certificati per 4 classi, come avviene solitamente nei corsi di sicurezza. Verranno scaricati circa 80 file nella cartella download mischiandosi con gli altri file. Generiamo invece uno zip con dentro gli 80 file, in modo che possano essere decompressi in una cartella apposita

**Comment by profmancusoa** [comment]
- ok speriamo che poi chi userà sarà in gradi di "unzippare il file" per poter accedere agli attestati
- fare però lo zip solo se gli attestati sono maggiori di N (5? 10?)
