### ISSUE TITLE
Sveltizzazione dei componenti necessari di tabler

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#2]
- coordinarsi con gli owner delle altre issue per stilare una lista minima di componenti tabler da "sveltizzare"
- la prima sveltizzazione la facciamo interna al progetto e non come npm separate per ragioni di efficienza dello sviluppo

Lista pronta per Lunedì 10/10

**Comment by Andrea-Canale** [comment]
Navbar: https://github.com/ittagnelli/Stabler/blob/main/src/lib/LeftBar.svelte
