### ISSUE TITLE
issue con pagina valutazioni

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#24]
client-manifest.js:18 SyntaxError: The requested module '/src/js/store.js' does not provide an export named 'page_action' (at +page.svelte? [sm]:3:39)

**Comment by profmancusoa** [comment]
- la pagina valutazione non fa quel che dovrebbe
- la pagina deve permettere l'inserimento di una valutazione da parte di un Utente per uno specifico PCTO
- idUtente è l'utente che fa la valutazione
- pcto è il PCTO valutato
- valutatore è una stringa che è STUDENTE || TUTOR
- voto è un int per il momento

Aggiornare CRUD in modo concorde a quanto descritto

**Comment by Andrea-Canale** [comment]
Risolto con la pull request #29

**Comment by profmancusoa** [comment]
grazie
