### ISSUE TITLE
TOTALE ORE PCTO

### ISSUE THREAD

**Issue by Bramoso-Tommaso** [ittagnelli/SARP#242]
Nella vista PCTO, più in particolare nella sezione delle presenze, in alto a sinistra c'è un accomulatore di ore PCTO
("TOTALE ORE PCTO: <X>") che non fa quello che dovrebbe fare ovvero accumulare tutte le ore di pcto approvate

**Comment by profmancusoa** [comment]
ciao, mi spieghi meglio il problema e come dovrebbe comportarsi

**Comment by Bramoso-Tommaso** [comment]
in alto a sinistra nella sezione delle presenze di pcto è presente un contatore che si chiama "TOTALE ORE PCTO" che segna sempre 0 ore, nonostante me ne siano già state approvate diverse di ore pcto... sostanzialmente il counter delle ore che è presente mano a mano che le ore vengono approvate dovrebbe fare la somma tra tutte le ore, non so se mi sono spiegato... al massimo a lezione le faccio vedere meglio la questione

**Comment by profmancusoa** [comment]
@Bramoso-Tommaso chiarissimo.
Io propongo di modificare e visualizzare il totale ore approvate e il totale ore registrate

**Comment by profmancusoa** [comment]
fatto
