### ISSUE TITLE
Vulnerabilità Convert to print 

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#245]
Se noi proviamo ad accedere a convert to print senza essere registrati la pagina appare lo stesso senza restituire 401.
https://sarp.agnelli.it/tools/convert-to-print

**Comment by profmancusoa** [comment]
. @Andrea-Canale il problema è anche presente in https://sarp.agnelli.it/verifica_stato

**Comment by profmancusoa** [comment]
fatto
