### ISSUE TITLE
script inserimento e update materie classi

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#252]
- necessario creare uno script che dato un file excel come quello allegato sia in grado di:
-  inserire le materie
- l'associazione docente, classe, materia e anno scolastico
- lo script deve essere in grado di aggiornare entry già esistenti per un dato anno scolastico
- se cambia anno scolastico non è un aggiornamento ma una nuova entry

[2022_materie_classi_docenti.xlsx](https://github.com/ittagnelli/SARP/files/11003823/2022_materie_classi_docenti.xlsx)

**Comment by profmancusoa** [comment]
Ok certo

Il sab 18 mar 2023, 13:11 Andrea Canale ***@***.***> ha
scritto:

**Comment by Andrea-Canale** [comment]
fatto

**Comment by Andrea-Canale** [comment]
https://github.com/ittagnelli/SARP/tree/issue252

**Comment by profmancusoa** [comment]
refactory completo
