### ISSUE TITLE
refactoring view valutazioni

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#31]

**Comment by profmancusoa** [comment]
- valutazioni cambia destinazione e ora rappresenta il modulo di gradimento dello studente nei confronti del PCTO

**Comment by profmancusoa** [comment]
per favore aggiungi una stima del tempo di risoluzione di questa issue

**Comment by Garabello-Marco** [comment]
ETA: 28/11

**Comment by profmancusoa** [comment]
come procede?

**Comment by Garabello-Marco** [comment]
meglio, alla fine con l'id multiplo non riesco a venirne a capo.
ho quindi deciso di assegnare un id incrementale alla tabella

**Comment by profmancusoa** [comment]
- refactor completo della view valutazioni fatto

**Comment by profmancusoa** [comment]
@Bramoso-Tommaso puoi testare a fondo la view valutazioni?

- cerca di verificare se funziona corettamente anche a livello logico
- PEr esempio uno studente può valutare un PCTO a cui non è iscritto e non ha partecipato?
