### ISSUE TITLE
Programmazione Classe

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#318]
i programmi vengono visualizzati validi per tutte le classi anche se in realtà non sono completi
se si stampa si ottiene un file vuoto (solo template)

![image](https://github.com/ittagnelli/SARP/assets/111191978/2dcf03ba-ac92-4e5f-aa92-7847779ce9e9)

Si devono visualizzare tutte le programmazioni con l'indicazione corretta di completezza

**Comment by Andrea-Canale** [comment]
I test sono stati fatti su quale DB? Produzione o sviluppo? Perchè il rilevamento dei programmi completati si basa sugli insegnamenti in tabella e se non sono presenti insegnamenti la classe risulta completa (0 insegnamenti == 0 insegnamenti con il flag completo)

**Comment by profmancusoa** [comment]
ok mi sta bene che le classi devono avere almeno un insegnamento
pertanto chiudo il bug
