### ISSUE TITLE
Vulnerabilità grave in convert-to-print(shell execution)

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#331]
Caricando un file sul convert-to-print con una sostituzione shell nel filename il comando verrà eseguito

Per provare: Creare un file chiamato attestato_formazione_$(comando_prova).docx dal file manager e Quando verrà eseguita la conversione guardare la console, uscirà comando_prova: command not found

**Comment by profmancusoa** [comment]
@Andrea-Canale come discusso risolviamo utilizzando un nome di file temporaneo

**Comment by profmancusoa** [comment]
ottimo lavoro
