### ISSUE TITLE
Creazione Wiki

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#34]
Secondo me dovremmo mettere delle istruzioni per chi non sa ancora bene come usare prisma e in generale per chi non ha mai inizializzato il progetto.
@profmancusoa cosa ne pensa?

**Comment by profmancusoa** [comment]
Totalmente d'accordo.
Anzi ti propongo di creare il wiki del progetto, così ogni applicazione (PCTO, PDP, etc etc) avrà una sezione del wiki

e li possiamo includere:
- documentazione pe rogni applicazione
- documentazione generale
- etc

**Comment by profmancusoa** [comment]
anche se lascerei questa parte a membri del team meno skillati

**Comment by profmancusoa** [comment]
per favore aggiungi una stima del tempo di risoluzione di questa issue

**Comment by Andrea-Canale** [comment]
Stima: 1 giorno o massimo 2 giorni

**Comment by Andrea-Canale** [comment]
Per adesso ho aggiunto:

- I dettagli del progetto(framework usati, informazioni generiche)
- Descrizione delle varie pagine
- Come funziona prisma e come riempire il DB

@profmancusoa  Manca altro? Adesso la faccio vedere anche a @MarcoCellini per vedere se si riesce a capire bene

**Comment by profmancusoa** [comment]
io non vedo nulla nel wiki.

**Comment by profmancusoa** [comment]
![image](https://user-images.githubusercontent.com/111191978/204033014-9f18e145-d133-4499-b311-d42eb202cbfe.png)

**Comment by Andrea-Canale** [comment]
L'avevo sviluppata su un branch a parte, comunque ora ho trasferito tutto sulla github Wiki

**Comment by profmancusoa** [comment]
Prova a chiedere a Seba P e Liccia se e' chiaro.

Grazie


Il ven 25 nov 2022, 10:37 Andrea Canale ***@***.***> ha
scritto:

**Comment by profmancusoa** [comment]
@Andrea-Canale puoi aggiungere come primissima cosa una breve descrizione su come:
1- fare il clone del repository
2- come generare un PAT
3- come configurare il proprio account, email e credential store
4- come installare le dipendenze
5- sostituire prisma migrate ..init con prisma db puish (non dobbiamo generare una nuova migrazione)
6 - come far partire il progetto e aprirlo nel browser

grazie

**Comment by Andrea-Canale** [comment]
Ho aggiornato la wiki e aperto la pull request #40 per rispettare alcune sezioni della wiki

**Comment by Andrea-Canale** [comment]
@profmancusoa un PAT sarebbe?

**Comment by profmancusoa** [comment]
Ma il wiki richiede PR? Credevo che bastasse editarlo

Il sab 26 nov 2022, 11:59 Andrea Canale ***@***.***> ha
scritto:

**Comment by Andrea-Canale** [comment]
Ho aggiunto dei nuovi file in tests
