### ISSUE TITLE
Impossibile rimuovere primo sotto-sotto argomento

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#377]
- Il template e la programmazione docente prevedono come obbligatorio solo 1 argomento per trimestre e 1 argomento per pentamestre
- tutti gli altri sotto-livelli devono poter essere eliminati con il cestino

![image](https://github.com/ittagnelli/SARP/assets/111191978/20dd119e-cd53-478d-9f67-afeabff1008b)

**Comment by profmancusoa** [comment]
![image](https://github.com/ittagnelli/SARP/assets/111191978/b6433a26-f13e-4137-9b84-8f1f3c32d7ed)

prova a guardare dinuovo

**Comment by Andrea055** [comment]
Per cancellare il sotto sotto argomento basta lasciare l'input vuoto e nel submit verrà rimosso

**Comment by profmancusoa** [comment]
ok va bene così, asusmiamo che ogni argomento abbia almeno 1 sotto argomento
