### ISSUE TITLE
studio dell'applicazione PCTO

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#38]
- studiare e sperimentare l'applicazione PCTO
- capire quali sono i componenti utilizzati e come interagiscono
- obiettivo è poi poter mettere mani al codice per il bug fixing

**Comment by profmancusoa** [comment]
come procede?

**Comment by lorenzo-rizzolo** [comment]
Io e cellini ci siamo messi d’accordo che martedì pomeriggio ci fermiamo a
scuola (con lei se c’è) per vederlo.

Il giorno ven 9 dic 2022 alle 16:23 Prof. Mancuso Antonio <
***@***.***> ha scritto:

**Comment by profmancusoa** [comment]
ok mi pare però che stiate lavorando poco o niente.

Martedì sono 3 settimane che abbiamo iniziato le issue con il nuovo gruppo di lavoro

**Comment by profmancusoa** [comment]
- chiudo questo issue in quanto dopo vari mesi dovreste essere al passo con sveltekit e dovreste conoscerfe l'applicazione PCTO bene
