### ISSUE TITLE
Implementare criptazione campi sensibili in DB

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#41]
@profmancusoa Stavo pensando, sempre riguardo la issue #37 che sarebbe meglio criptare le informazioni personali nel DB come nome, cognome o telefono.
Cosa ne pensa?

**Comment by profmancusoa** [comment]
direi che non è necessario. Il DB non c'è lo permette e implementarlo server side è macchinoso e pone sempre il problema delle chiavi di sicurezza
