### ISSUE TITLE
Aggiungere Header HTTP nel file app.html

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#42]
Sempre riguardo la issue #37 dovremmo aggingere nel file HTML di base(app.html) tutti i tag per prevenire alcuni attachi.
- Creare un Content Security Policy
- X-Frame options
- Strict-Transport-Security
- Access-Control-Allow-Origin

@Emanuele-Furina Cosa ne pensi? Ne mancono alcuni?
L'unico problema è che alcuni header andranno messi lato web server, a tal proposito potrebbe essere utile tracciare sulla repo il file di configurazioni nginx, oppure aggiungere alcuni di questi header nel file svelte.config.js considerato che nginx sarà solo il reverse proxy

**Comment by Emanuele-Furina** [comment]
Direi che c'è tutto, non ho nulla da aggiungere
