### ISSUE TITLE
Aggiungere validazione server side form

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#43]
- è necessaria anche una validazione server side

**Comment by Andrea-Canale** [comment]
@profmancusoa posso risolverla io?

**Comment by profmancusoa** [comment]
fai la validazione per un solo form e fammi evdere come viene prima di farle per tutte le altre
usa you come ho usato per il client side e cerca di capire come possiamo condividere il  modello di validazione tra client e server

**Comment by Andrea-Canale** [comment]
Ho creato il branch https://github.com/ittagnelli/SARP/tree/canale/security/sanitize
Per ora la validazione c'è solo nella pagina delle aziende, non tutte sono state fatte server-side, per ridurre il carico sul server. Solo le verifiche dove dobbiamo essere sicuri di avere un dato attendibile sono state fatte dal client

**Comment by profmancusoa** [comment]
- ho visto che hai modificato la validazione lato client. direi di concentrarci solo su quello che richiede la issue e cioè il lato server
- non mi è chiaro il tipo di validazione che hai fatto lato server.
- dobbiamo trovare un modo che usi la stessa validazione lato client altrimenti dobbiamo duplicare sempre il codice
- prova a pensare meglio come poter validare i dati sia lato client che lato server usando yup (schema validator)
- rimuovi le modifiche lato client e concentrati solo sul lato server
grazie

**Comment by profmancusoa** [comment]
- guarda come funziona ora SARP con la gestione delle sessioni ed autenticazione
-  ora se non sei autenticato e quindi hai una sessione regolare non puoi interagire con il sistema anche lato backend, questo dovrebbe darci un ottimo grado di sicurezza nel neso che solo utenti validi possono scrivere nel DB
- per esempio aggiungete con FUrina dei test di sicurezza che provano a bypassare il meccanismo di login e della sessione. questo è sicuramente utile

**Comment by Andrea-Canale** [comment]
appena abbiamo i test di sicurezza risolvo la issue

**Comment by profmancusoa** [comment]
Ok va benissimo

Grazie

Il gio 22 dic 2022, 20:34 Andrea Canale ***@***.***> ha
scritto:

**Comment by profmancusoa** [comment]
chiudo questa issue in quanto al momento non rilevante
