### ISSUE TITLE
PCTO Stage rimozione lista iscritti dalla tabella principale

### ISSUE THREAD

**Issue by profmancusoa** [ittagnelli/SARP#469]
- rimuovere la colonna iscritti in quanto ormai le imamgini degli studenti sono obsolete in quanto non presenti per tutti i nuovi iscritti dal 2023

**Comment by profmancusoa** [comment]
qualche novità??

**Comment by Rossi-Tommaso** [comment]
Più tardi provo a fare qualcosa, domani la aggiorno su quello che sono riuscito a fare

**Comment by profmancusoa** [comment]
![image](https://github.com/ittagnelli/SARP/assets/111191978/3d16223f-73e2-44dc-8dc9-fbe3589b50b7)

**Comment by profmancusoa** [comment]
closed
