### ISSUE TITLE
Tabelle documento PDP generato

### ISSUE THREAD

**Issue by Romano-Gabriele** [ittagnelli/SARP#543]
Nel documento PDP in formato docx, generato premendo sull'icona di stampa nella sezione PDP Alunni, al punto 1 della SEZIONE C del documento (Osservazione di Ulteriori Aspetti Significativi) le griglie riportano opzioni errate rispetto a quelle inserite dal TUTOR e dallo STUDENTE.
Pare che l'ordine delle intestazioni delle tabelle sia invertito.

**Comment by profmancusoa** [comment]
risolto. 
@Romano-Gabriele rifai il test e fammi sapere se vedi il problema scomparso.

Se si chiudi questa issue

**Comment by Romano-Gabriele** [comment]
a seguito dei test eseguiti le confermo che il bug è stato risolto
