### ISSUE TITLE
Typo footer tabelle

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#58]
Segnalo un typo su tutte le tabelle delle paginei:
![image](https://user-images.githubusercontent.com/99402143/206251461-48680095-f8c3-4d06-aef3-0625a149ab7f.png)
Dovrebbe essere: Ci sono N utenti attivi

**Comment by MarcoCellini** [comment]
prof, ho fatto la PR per questo errore, va bene??
