### ISSUE TITLE
Chiudere la connessione al db

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#59]
Noi non chiudiamo mai la connessione con il DB, la conseguenza è che si aprono sempre nuovi client prisma e ci viene mandato un warning

`warn(prisma-client) There are already 10 instances of Prisma Client actively running.`

Propongo di aggiungere ad ogni endpoint alla fine la seguente funzione

`await SARP.$disconnect();`

**Comment by profmancusoa** [comment]
come si riproduce questo bug?

prima di riolverlo dobbiamo capire come riprodurlo per verificare poi che in effetti il fix funziona

questo è un esempio perfetto per un test automatico.

che ne dici?

**Comment by Andrea-Canale** [comment]
Per riprodurre il bug bisogna fare 10 richieste al DB penso, quindi anche solo 10 GET ad una view.
Sicuramente si può scrivere un test, penso sia importante perchè ad un certo punto se le connessioni non vengono chiuse il db si satura, o almeno su MySQL o SQL Server, non so se SQLite abbia un limite

**Comment by profmancusoa** [comment]
io ho provato decine di volte ma non vedo nessun problema.

Prova a capire come riprodurlo e fornisci qui una procedura per riprodurre il bug

**Comment by profmancusoa** [comment]
-   @Andrea-Canale  sei riuscito a riprodurre questo bug?

**Comment by profmancusoa** [comment]
@Andrea-Canale leggi qui [non chiudere la connessione](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prismaclient-in-long-running-applications)

**Comment by profmancusoa** [comment]
@Andrea-Canale puoi guardare SARP 0.5.0? Ho creato un singleton per la connessione al DB, quindi ora non è necessario fare nulla ne chiudere nessuna connessione in quanto ci sarà sempre una sola connessione aperta

- [ ] per favore verifica e se ok, chiudiamo questo issue
grazoe
