### ISSUE TITLE
Aggiungere gestione delle eccezioni

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#60]
Dovremmo aggiungere dei trycatch in ogni inserimento per notificare all'utente eventuali errori. Come ad esempio nella pagine delle aziende nel branch canale/security/sanitize

**Comment by profmancusoa** [comment]
come riprodurre questo problema?

**Comment by Andrea-Canale** [comment]
Per esempio se il numero viene digitato male dall'utente e risulta duplicato([violazione unique](https://github.com/ittagnelli/SARP/blob/main/prisma/schema.prisma#L100)) deve essere visualizzato un alert come ho fatto nel branch canale/security/sanitize, devo solo mettere l'alert di tabler perchè ora c'è quello del browser. Poi, secondo me, se l'inserimento viene eseguito con successo deve esserci sempre un alert perchè se abbiamo 100 utenti la segretaria non vede come primo utente quello che ha appena inserito e quindi penserà di non averlo fatto.
Tipo così: https://github.com/ittagnelli/SARP/blob/canale/security/sanitize/src/routes/aziende/%2Bpage.server.js#L84

**Comment by profmancusoa** [comment]
non sono sicuro di aver capito.
a quale view ti riferisci? 

ti riferisci alla validazione del form di inserimento?

**Comment by Andrea-Canale** [comment]
Per dire se quando la segretaria metta un'azienda con un id duplicato il db va in errore e noi non lo segnaliamo all'utente. Questa può accadere non solo nelle view azienda ma anche su tutto le altre.

**Comment by profmancusoa** [comment]
- @Andrea-Canale ok ho capito. direi che ha senso
- ti assegno la issue, ma dobbiamo fare il possibile che il form sia validato correttamente in input

**Comment by Andrea-Canale** [comment]
Ho fatto una prova sulla pagina delle aziende, https://github.com/ittagnelli/SARP/tree/issue60/src/routes/aziende. Per evitare che il form venga cancellato in caso di id duplicato, ho creato un endpoint che controlla se l'id è già esistente così da segnalarlo all'utente e poi ho messo un trycatch che in caso di errore, lo riporta nel log

**Comment by profmancusoa** [comment]
- @Andrea-Canale  penso che dobbiamo avere una tecnica più sofisticata. per esempio possiamo salvare il contenuto del form o nel localstorage o ancora meglio nello store di svelte
- se si ritorna alla pagina con un errore dall'endpoint allora ricarichiamo il form dallo store
- il metodo dell'endpoint che hai descritto genere un round trip tra client e server non necessario
- prova a capire se l'implementazione come ti ho suggerito è fattibile
- non pensare ad un solo caso (azienda) ma a tutte le viste esistenti e future
- grazie
-

**Comment by Andrea-Canale** [comment]
Ho implementato un sistema del genere sulla view aziende, se va bene lo metto anche sulle altre: https://github.com/ittagnelli/SARP/tree/canale/issue60
Salva il form nel localstorage e in caso di errore lo ricarica, lo store di svelte si resetta al refresh della pagina quindi non possiamo usarlo. Appena riesco implemento anche l'id progressivo #97

**Comment by profmancusoa** [comment]
- ok ho apportato varie modifiche per rimuovere l'alert
- cerca la stringa PROF: così vedi tutte le modifiche che ho fatto
- quando si genera uin erorre 500, viene visualizzato nella pagina così chi legeg puooi contattarci e riportare il problema
- lato client ho rimosso alert ed aggiunto un messaggio di errore dentro il modale
- penso che possiamo apportare queste modifiche alle viste (ad un certo punto ti hoo scritot di creare un componente)
- leggi bene i commenti e se ci sono dubbi fammi sapere

spero sia di aiuto

**Comment by profmancusoa** [comment]
-  @Bramoso-Tommaso è necessario unbel test estensivo (chiedi a @Andrea-Canale se hai bisogno di suggerimenti su come testare)
