### ISSUE TITLE
Bottone fantasma

### ISSUE THREAD

**Issue by Sebastiano-Racca** [ittagnelli/SARP#65]
Quando si esce da una pagina senza il bottone in altro a destra per andare in un'altra pagina, il bottone rimane lì, senza aggiornare parte dell'header.

### Step per riprodurre il bug
1. Effettua il login
2. Vai su una pagina contenente un bottone nell'header (in alto a destra)
3. Entra in un'altra pagina senza bottone

### Video dimostrativo
[bug](https://user-images.githubusercontent.com/84769196/206771277-5dfda2ce-aca7-4a24-ab96-e318672ba266.webm)

**Comment by MarcoCellini** [comment]
PR #124
