### ISSUE TITLE
Azienda fantasma

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/SARP#73]
Nella tabella azienda c'è un'azienda che nel db non è presente.
Per riprodurre il bug basta inizializzare il progetto ed andare sulla tab aziende
![image](https://user-images.githubusercontent.com/99402143/206847341-0f235616-d357-4d10-86fc-15caec8974ed.png)

**Comment by profmancusoa** [comment]
- il problema sta nell'aggiunta della sessione. in altre parole all'oggetto che viene passato alla tabella, è aggiunta una nuova linea che contiene la sessione.
- questa è la linea fantasma che appare ora in tutte le tabelle

**Comment by profmancusoa** [comment]
- risolto con la PR per issue#48
