### ISSUE TITLE
formato email non corretto

### ISSUE THREAD

**Issue by Bramoso-Tommaso** [ittagnelli/SARP#76]
Nella vista utenti, nella creazione di un utente, metterei come elemento obbligatorio la @ o ancora meglio un formato email (nome.cognome@...)

**Comment by MarcoCellini** [comment]
https://github.com/ittagnelli/SARP/pull/88

**Comment by profmancusoa** [comment]
verificare se è risolto

**Comment by Bramoso-Tommaso** [comment]
@MarcoCellini lato client

**Comment by MarcoCellini** [comment]
Comunque ho già risolto, guarda la Pr

**Comment by Bramoso-Tommaso** [comment]
appena visto, funziona tutto correttamente, bravo @MarcoCellini
