### ISSUE TITLE
formato incorretto del numero telefonico

### ISSUE THREAD

**Issue by Bramoso-Tommaso** [ittagnelli/SARP#77]
durante l'inserimento del numero telefonico nella vista utenti, metterei come elemento obbligatorio il formato dello stesso, quindi che magari il numero inizi con il "+39" oppure che le cifre inserite non siano più o meno di 10 (numero obbligatorio per tutti i numeri di telefono), es. "3338120708", non quindi magari "98" oppure "7483284294258340345873573852393".

**Comment by MarcoCellini** [comment]
https://github.com/ittagnelli/SARP/pull/88

**Comment by profmancusoa** [comment]
@Bramoso-Tommaso fare regression test: verificare se il fix risolve veramente il problema

**Comment by Bramoso-Tommaso** [comment]
appena fatto il pull della repo, aggiornamenti eseguiti correttamente @MarcoCellini , bravo
