### ISSUE TITLE
possibilità di inserire cifre e caratteri speciali nel nome e nel cognome

### ISSUE THREAD

**Issue by Bramoso-Tommaso** [ittagnelli/SARP#78]
nella vista utenti, in SARP, toglierei la possibilità di inserire nome e cognome contenenti delle cifre, dunque obbligherei l'utente ad inserire nel nome e nel cognome solo ed esclusivamente dei caratteri, non quindi delle cifre ("5673214"), o caratteri strani come (ç#é*§°).

**Comment by MarcoCellini** [comment]
https://github.com/ittagnelli/SARP/pull/88

**Comment by profmancusoa** [comment]
@Bramoso-Tommaso : fare regression test

**Comment by Bramoso-Tommaso** [comment]
ottimo lavoro @MarcoCellini  ho appena verificato e ora non è più possibile inserire caratteri speciali, ma solamente delle lettere sia nel nome che nel cognome
