### ISSUE TITLE
numero di utenti attivi

### ISSUE THREAD

**Issue by Bramoso-Tommaso** [ittagnelli/SARP#79]
in SARP, nella vista utenti, ho provato a fare un test rimuovendo tutti gli utenti lasciandone uno solo ed ho notato una banale piccolezza.
Il numero di utenti scritto in basso a sinistra è al plurale nonostante ci sia un solo utente attivo --> "Ci sono 1 utenti attivi" ed invece quando concretamente ne è presente uno solo dovrebbe essere: "C'è 1 utente attivo".

**Comment by profmancusoa** [comment]
pare sensato

**Comment by profmancusoa** [comment]
@Bramoso-Tommaso verifica se questo fix risolve l'issue che hai aperto.

**Comment by Bramoso-Tommaso** [comment]
ho appena provato ed il problema persiste

**Comment by Sebastiano-Racca** [comment]
> ho appena provato ed il problema persiste

Hai fatto il pull della repo?

**Comment by Bramoso-Tommaso** [comment]
sì, lo ho appena eseguito e teoricamente funziona tutto correttamente, bravo seba
