### ISSUE TITLE
eliminazione del proprio stesso profilo

### ISSUE THREAD

**Issue by Bramoso-Tommaso** [ittagnelli/SARP#86]
in SARP, nella vista utenti, ho provato a rimuovere il mio utente stesso, e facendolo, il programma va in una sorta di "crush" facendo comparire a schermo l'errore "500" con la faccina triste, metterei che quando un utente tenta di rimuovere se stesso, gli venga scritto a schermo che è presente un errore e che è impossibile rimuovere quell'utente.

**Comment by profmancusoa** [comment]
- necessario aggiungere un messaggio di errore adeguato magari visualizzandolo in un modale o altra forma
