### ISSUE TITLE
Foto profilo nelle tabelle

### ISSUE THREAD

**Issue by MarcoCellini** [ittagnelli/SARP#89]
Nelle tabelle sarebbe bello vedere la foto profilo relativa ad ogni singolo utente. Se l'utente non ha la foto profilo se ne mette una di default (a vostra scelta).

**Comment by profmancusoa** [comment]
@Sebastiano-Racca @Paolo-Garabello come procede?

**Comment by profmancusoa** [comment]
- @MarcoCellini duplicato della issue #45
