### ISSUE TITLE
Validazione form per tutte le viste

### ISSUE THREAD

**Issue by MarcoCellini** [ittagnelli/SARP#90]
Come fatto in precedenza eseguire il controllo dei dati prima dell' immisione nelle tabelle (lato client).

**Comment by Bramoso-Tommaso** [comment]
@profmancusoa funziona tutto correttamente, ho appena testato nella vista utenti l'inserimento di essi con vari parametri e non ho riscontrato nessun problema

**Comment by profmancusoa** [comment]
Puoi provare tutte le viste? Non solo utenti

Il ven 23 dic 2022, 12:57 Bramoso-Tommaso ***@***.***> ha
scritto:
